"""
Patient Dispatch & Follow-Up Service (Person D / Person B integration)
Handles SMS/WhatsApp diagnosis delivery and follow-up scheduling for ASHA/PHC workflow.
"""

import json
import logging
from datetime import datetime, timedelta
from typing import Dict, Any, List, Optional

logger = logging.getLogger(__name__)


class DispatchService:
    """Service for sending patient diagnosis via SMS/WhatsApp and managing follow-ups."""

    def __init__(self):
        self.callbacks_sent = 0

    def format_sms(self, record: Dict[str, Any], doctor_info: Optional[Dict[str, Any]] = None) -> str:
        """Generates standard GSM SMS text for the patient/guardian (concise, <= 160 chars)."""
        p_name = record.get("full_name") or record.get("patient", {}).get("full_name", "Patient")
        color = record.get("triage_color") or record.get("assessment", {}).get("triage_color", "GREEN")
        diag = record.get("diagnosis") or record.get("assessment", {}).get("diagnosis", "Clinical Assessment")
        urgency = record.get("urgency") or record.get("assessment", {}).get("urgency", "Home Care")
        doc_phone = (doctor_info or {}).get("phone_number", "+919876543210")
        
        if color == "RED":
            return f"[MoHFW ASHA Alert] {p_name}: EMERGENCY RED FLAG ({diag}). Rush to nearest PHC/Hospital immediately. Keep warm. Doctor: {doc_phone}"
        elif color == "YELLOW":
            return f"[MoHFW ASHA] {p_name}: {diag}. Visit PHC Clinic within 24h for checkup. Start ORS/Fluids. Emergency Helpline: {doc_phone}"
        else:
            return f"[MoHFW ASHA Care] {p_name}: {diag} ({urgency}). Continue feeding, fluids/ORS. Watch for fast breathing or lethargy. PHC Helpline: {doc_phone}"

    def format_whatsapp(self, record: Dict[str, Any], doctor_info: Optional[Dict[str, Any]] = None) -> str:
        """Generates structured, comprehensive WhatsApp Clinical Care Report for patient/guardian."""
        p_name = record.get("full_name") or record.get("patient", {}).get("full_name", "Patient")
        p_id = record.get("patient_id") or record.get("patient", {}).get("patient_id", "P-101")
        age = record.get("age_months") or record.get("patient", {}).get("age_months", 12)
        color = record.get("triage_color") or record.get("assessment", {}).get("triage_color", "GREEN")
        diag = record.get("diagnosis") or record.get("assessment", {}).get("diagnosis", "Clinical Assessment")
        urgency = record.get("urgency") or record.get("assessment", {}).get("urgency", "Home Care")
        actions = record.get("actions") or record.get("assessment", {}).get("actions", [])
        
        doc = doctor_info or {
            "full_name": "Dr. Anjali Deshmukh, MD",
            "phc_name": "Khed Sub-District PHC",
            "phone_number": "+91 98765 43210"
        }

        icon = "🚨 RED ALERT" if color == "RED" else ("🟡 YELLOW ALERT" if color == "YELLOW" else "🟢 GREEN (STABLE)")
        
        msg = [
            f"🏥 *GOVT OF INDIA / MoHFW TELE-TRIAGE REPORT*",
            f"━━━━━━━━━━━━━━━━━━━━━",
            f"👶 *Patient:* {p_name} (Age: {age} months, ID: {p_id})",
            f"📊 *Triage Level:* {icon}",
            f"🩺 *Clinical Diagnosis:* {diag}",
            f"⏱️ *Urgency:* {urgency}",
            f"",
            f"📋 *HOME CARE & ACTION PLAN:*"
        ]
        
        if actions:
            for a in actions[:3]:
                msg.append(f" • {a}")
        else:
            msg.append(" • Continue frequent fluids, breastfeeds & ORS.")
            msg.append(" • Monitor temperature and breathing twice daily.")

        msg.extend([
            f"",
            f"⚠️ *DANGER SIGNS (Rush to PHC if seen):*",
            f" • Inability to drink or breastfeed",
            f" • Chest indrawing / fast breathing",
            f" • Convulsions / severe lethargy / vomiting everything",
            f"",
            f"👩‍⚕️ *Appointed Medical Officer:*",
            f"{doc['full_name']} • {doc['phc_name']}",
            f"📞 *Emergency Contact:* {doc['phone_number']}",
            f"━━━━━━━━━━━━━━━━━━━━━",
            f"_This report is generated by your village ASHA worker via the offline AI Tele-Triage System._"
        ])
        return "\n".join(msg)

    def schedule_followup(
        self,
        patient_id: str,
        assessment_id: str,
        follow_up_date: str,
        follow_up_notes: str = "",
        doctor_id: str = "DOC-PUNE-01",
    ) -> Dict[str, Any]:
        """Schedules a follow-up appointment for the patient."""
        try:
            follow_up_datetime = datetime.fromisoformat(follow_up_date)
        except ValueError:
            follow_up_datetime = datetime.utcnow() + timedelta(days=3)

        return {
            "followup_id": f"FUP-{datetime.utcnow().strftime('%Y%m%d%H%M%S')}",
            "patient_id": patient_id,
            "assessment_id": assessment_id,
            "doctor_id": doctor_id,
            "follow_up_date": follow_up_datetime.isoformat() + "Z",
            "follow_up_notes": follow_up_notes,
            "status": "SCHEDULED",
            "created_at": datetime.utcnow().isoformat() + "Z",
        }

    def get_pending_followups(self, followups: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """Returns follow-ups that are pending or due soon."""
        now = datetime.utcnow()
        pending = []
        for f in followups:
            try:
                fup_date = datetime.fromisoformat(f["follow_up_date"].replace("Z", ""))
                if f["status"] == "SCHEDULED" and fup_date >= now:
                    pending.append(f)
                elif f["status"] == "SCHEDULED" and fup_date < now:
                    f["status"] = "OVERDUE"
                    pending.append(f)
            except (ValueError, KeyError):
                continue
        return pending

    def mark_followup_completed(self, followup_id: str, followups: List[Dict[str, Any]]) -> Optional[Dict[str, Any]]:
        """Marks a follow-up as completed."""
        for f in followups:
            if f.get("followup_id") == followup_id:
                f["status"] = "COMPLETED"
                f["completed_at"] = datetime.utcnow().isoformat() + "Z"
                return f
        return None


_dispatch_service: Optional[DispatchService] = None


def get_dispatch_service() -> DispatchService:
    """Get or create the global DispatchService instance."""
    global _dispatch_service
    if _dispatch_service is None:
        _dispatch_service = DispatchService()
    return _dispatch_service
